WebRegistroLibros/Models/ErrorViewModel.cs
namespace WebRegistroLibros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebRegistroLibros/Models/Libro.cs
using System.ComponentModel.DataAnnotations;

namespace WebRegistroLibros.Models
{
    public class Libro
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(50, ErrorMessage = "El {0} debe ser almenos {2} y maximo {1} caracteres", MinimumLength = 3)]
        [Display(Name = "Titulo")]
        public string Titulo { get; set; } 

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(50, ErrorMessage = "El {0} debe ser almenos {2} y maximo {1} caracteres", MinimumLength = 3)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Lanzamiento")]
        public DateTime FechaLanzamiento { get; set; }

        [Required(ErrorMessage = "El Autor es obligatorio")]

        public string Autor { get; set; }

        [Required(ErrorMessage = "El Precio es obligatorio")]
        public int Precio { get; set; }
    }
}

WebRegistroLibros/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebRegistroLibros.Models;

namespace WebRegistroLibros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebRegistroLibros/Controllers/LibroController.cs
using Microsoft.AspNetCore.Mvc;
using WebRegistroLibros.Data;
using WebRegistroLibros;
using WebRegistroLibros.Models;
using WebRegistroLibros.Hubs;
using Microsoft.AspNetCore.SignalR;
using Rotativa.AspNetCore;

namespace WebRegistroLibros.Controllers
{
    // Define una clase llamada LibroController que hereda de la clase Controller proporcionada por ASP.NET Core.
    public class LibroController : Controller
    {
        // Declara una variable privada readonly llamada _context que almacena una instancia de ApplicationDbContext.
        private readonly ApplicationDbContext _context;
        private readonly IHubContext<NotificacionHub> _hubContext;

        // Constructor de la clase LibroController que recibe una instancia de ApplicationDbContext a través de la inyección de dependencias.
        public LibroController(ApplicationDbContext context, IHubContext<NotificacionHub> hubContext)
        {
            _context = context;
            _hubContext = hubContext;
        }

        // Método de acción para la ruta "Index".
        public IActionResult Index()
        {
            // Obtiene una lista de objetos Libro desde la base de datos a través del contexto.
            IEnumerable<Libro> listaLibros = _context.Libro;

            // Retorna una vista con la lista de libros.
            return View(listaLibros);
        }

        // Método de acción HTTP GET para la ruta "Create".
        public IActionResult Create()
        {
            // Retorna la vista para crear un nuevo libro.
            return View();
        }

        // Método de acción HTTP POST para la ruta "Create" que recibe los parámetros del formulario.
        [HttpPost]
        public IActionResult Create(Libro libro)
        {
            // Verifica si el modelo recibido es válido.
            if (ModelState.IsValid)
            {
                // Agrega el objeto libro al contexto y guarda los cambios en la base de datos.
                _context.Libro.Add(libro);
                _context.SaveChanges();

                var mensaje = "Se ha agregado un nuevo libro: " + libro.Titulo;
                _hubContext.Clients.All.SendAsync("RecibirNotificacion", mensaje);
                Console.WriteLine("Notificación enviada: " + mensaje);


                // Establece un mensaje en TempData para mostrar en la vista.
                TempData["mensaje"] = "El libro se ha guardado correctamente";

                // Redirige a la acción "Index".
                return RedirectToAction("Index");
            }

            // Si el modelo no es válido, vuelve a la vista de creación.
            return View();
        }

        // Métodos de acción para la edición de un libro.

        // Método HTTP GET para la ruta "Edit" que recibe un ID como parámetro.
        public IActionResult Edit(int? id)
        {
            // Verifica si el ID es nulo o 0.
            if (id == null || id == 0)
            {
                return NotFound();
            }

            // Obtiene el libro correspondiente al ID desde el contexto.
            var libro = _context.Libro.Find(id);

            // Si no se encuentra el libro, retorna un error 404.
            if (libro == null)
            {
                return NotFound();
            }

            // Retorna la vista de edición con el libro.
            return View(libro);
        }

        // Método HTTP POST para la ruta "Edit" que recibe los datos del formulario de edición.
        [HttpPost]
        public IActionResult Edit(Libro libro)
        {
            if (ModelState.IsValid)
            {
                // Actualiza el libro en el contexto y guarda los cambios.
                _context.Libro.Update(libro);
                _context.SaveChanges();

                TempData["mensaje"] = "El libro se ha actualizado correctamente";

                // Redirige a la acción "Index".
                return RedirectToAction("Index");
            }

            return View();
        }

        // Métodos de acción para la eliminación de un libro.

        // Método HTTP GET para la ruta "Delete" que recibe un ID como parámetro.
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound();
            }

            return View();
        }

        // Método HTTP POST para la ruta "Delete" que recibe el ID de un libro a eliminar.
        [HttpPost]
        public IActionResult DeleteLibro(int? id) /*la palabra deletelibro debe ser singular*/
        {
            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound(null);
            }

            // Elimina el libro del contexto y guarda los cambios.
            _context.Libro.Remove(libro);
            _context.SaveChanges();

            TempData["mensaje"] = "El libro se ha Eliminado";

            // Redirige a la acción "Index".
            return RedirectToAction("Index");
        }

        //Imprimir PDF
        public IActionResult GeneratePdf(int id)
        {
            var libros = _context.Libro.Find(id);

            if (libros == null)
            {
                return NotFound();
            }

            // Genera el PDF utilizando la vista "PdfView" y el modelo del libro.
            var pdf = new ViewAsPdf("Index", new List<Libro> { libros})
            {
                FileName = "Libro.pdf", // Nombre del archivo PDF
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape, // Orientación de la página (opcional)
                PageSize = Rotativa.AspNetCore.Options.Size.A4, // Tamaño de la página (opcional)
            };

            return pdf;
        }
    }
}

WebRegistroLibros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebRegistroLibros/Views/Libro/Create.cshtml
@model WebRegistroLibros.Models.Libro

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

   <div class="row">
       <div class="col-sm-12">
           <h3>Crear un nuevo libro</h3>
       </div>
   </div>

   <div class="row">
       <div class="col-sm-10">
           <form method="post" asp-action="Create">
               <div asp-validation-summary="ModelOnly" class="text-danger"></div>
               <div class="form-group">
                   <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" /> @*  Se debe agregar la etiqueta input *@
                   <span asp-validation-for="Titulo" class="text-danger"></span> 
               </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for ="Descripcion" class="form-control" /> @*  Se debe agregar la etiqueta input *@
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for ="Autor" class="form-control" /> @*  Se debe agregar la etiqueta input *@
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for ="Precio" class="form-control" /> @*  Se debe agregar la etiqueta input *@
                    <span asp-validation-for="Precio " class="text-danger"></span>
                </div>

                <div class="from-group">
                    <input type="submit" value="Crear Libro" class="btn btn-primary" />
                </div>
            </form>
           
       </div>
   </div>

</div>

@section Scripts{
    @{<partial name="_validationScriptsPartial"/>
    }
}

WebRegistroLibros/Views/Libro/Delete.cshtml
@model WebRegistroLibros.Models.Libro
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml"; /* No esta completo la direccion del Layaout */
}

<div class="container"> @* se debe agregar container porque esta mal escrito *@

    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar Libro</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="DeleteLibro"> @* No es metodo get si no que post *@

                <input type="hidden" asp-for="Id" />

               

                <div class="from-group">
                    <input type="submit" value="Eliminar Libro" class="btn btn-primary" /> @* el type es submit no Hidden *@
                </div>

            </form>
        </div>
    </div>

</div>

@section Scripts{ @* la palabra Script debe ser plural *@
    @{
        <partial name="_validationScriptsPartial" />
    }
}

WebRegistroLibros/Views/Libro/Edit.cshtml
@model WebRegistroLibros.Models.Libro

@{
    ViewData["Title"] = "Editar Libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h3>Editar Libro</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit">

                <input type="hidden" asp-for="Id" />

                <div asp-validation-summary="ModelOnly" class="danger-text"></div>
                <div class="from-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="from-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="from-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="from-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio " class="text-danger"></span>
                </div>

                <div class="from-group">
                    <input type="submit" value="Editar Libro" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>

</div>

@section Scripts{
    @{
        <partial name="_validationScriptsPartial" />
    }
}

WebRegistroLibros/Views/Libro/Index.cshtml
@model IEnumerable<WebRegistroLibros.Models.Libro>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml"; /* No esta completo la direccion del Layaout */
}

<div class="container">
    <div id="notificacion-container"></div>

    @if (TempData["mensaje"] != null) //no es ==
    {
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"] @* es mensaje no menssage *@
                <button type="button" class="close" date-dismiss="alert" aria-label="Close"> @*  en lugar de type es button  *@
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @* </div> este div esta de más*@
    }

    <div class="rows">
        <div class="col-sm-6">
            <h3>Lista de Libros</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Libro">Agregar Nuevo Libro</a> @* es asp-controller, no asp-control y tambien el asp-action solo es un asp*@
        </div>
    </div>

    <div class="rows">
        @if (Model.Count() > 0) //(libro) y == no va, solo es Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.Id)</td> @* es IDLibro *@
                        <td>@Html.DisplayNameFor(m => m.Titulo)</td>  @* es m *@
                        <td>@Html.DisplayNameFor(m => m.Descripcion)</td>
                        <td>@Html.DisplayNameFor(m => m.FechaLanzamiento)</td>
                        <td>@Html.DisplayNameFor(m => m.Autor)</td>
                        <td>@Html.DisplayNameFor(m => m.Precio)</td> @* es m *@
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model) @* es item *@
                    {
                        <tr>
                            @* es item en todo*@
                            <td>@item.Id</td>
                            <td>@item.Titulo</td>
                            <td>@item.Descripcion</td>
                            <td>@item.FechaLanzamiento</td>
                            <td>@item.Autor</td>
                            <td>@item.Precio</td>
                            <td>

                               @*  //es <a asp-controller></a> *@
                                <a asp-controller="Libro" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a> @* asp-asp-route="@item.Id" no es; es: asp-route-id="@item.Id"*@
                                <a asp-controller="Libro" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                                <a asp-controller="Libro" asp-action="GeneratePdf" asp-route-id="@item.Id" class="btn btn-primary">Descargar PDF</a>
                            </td>
                            
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros</p>
        }
         
    </div>
   
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.11/signalr.min.js"></script>
<script>
    var connection = new signalR.HubConnectionBuilder()
        .withUrl("/notificacionHub") // Reemplaza con la ruta a tu Hub
        .build();

    connection.start().then(function () {
        console.log("Conexión a SignalR establecida.");
    }).catch(function (err) {
        console.error("Error al conectar a SignalR: " + err.toString());
    });

    connection.on("RecibirNotificacion", function (mensaje) {
        console.log("Notificación recibida: " + mensaje);
        // Aquí puedes mostrar la notificación en tu página web
        alert("Nueva notificación: " + mensaje);
    });
</script>

WebRegistroLibros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Página principal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebRegistroLibros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Libro" asp-action="Index">Web Registro de libros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebRegistroLibros - <a asp-area="" asp-controller="Libro" asp-action="Index">Registrar</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>